services:
  database:
    image: postgres:16-alpine
    container_name: risk_management_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: risco_db
    ports:
      - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
